### ISSUE TITLE
Storage location of custom cheat sheets

### ISSUE THREAD

**Issue by SebastianSchumann** [qirolab/Ctrl-Alt-Cheat-issues#3]
Where are self-created cheat sheets saved?
We would consider using this extension, but we have to distribute created cheat sheets to all users via Git.
The intention is to create cheat sheets for our own code and make it easier for other developers to work with it.
To do this, we would store the cheat sheet directly in the projects that are managed via Git.

At the moment, I don't see the created cheat sheets in the file overview of VS-Code.

**Comment by hkp22** [comment]
By default, the cheat sheets you create with the `Ctrl+Alt+Cheat` extension are stored in the user's home directory at the following path: `.vscode/qirolab/ctrl-alt-cheat`. However, you can modify this location through the VS Code settings.

To change the storage location of the cheat sheets, you can use the setting:

```json
"ctrl-alt-cheat.userCheatsheetPath": "your-custom-absolute-path"
```

Since you want to distribute created cheat sheets to all users via Git, I recommend setting up a shared project directory structure like this:

```
Your-Project/
  - /.vscode/
    - settings.json
    - /cheatsheets/
   
  ...
```

Then, in your `settings.json` file within the `.vscode` directory, configure the path as follows:

```json
{
    "ctrl-alt-cheat.userCheatsheetPath": "your-project-absolute-path/.vscode/cheatsheets"
}
```

By committing this configuration to your Git repository, you can ensure that all team members share the same cheat sheets, making it easier for everyone to access and maintain consistency in their development workflows.

I hope this helps! Please let me know if you have any other questions or need further assistance.

---
